version: '3.8'

services:
  springboot-backend:
    build: .
    container_name: regular-payments-dao
    ports:
      - "8080:8080"
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - springboot-postgresql-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/regular-payments-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  postgresql:
    image: postgres:latest
    container_name: regular_payments_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: regular-payments-db
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql
    networks:
      - springboot-postgresql-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresql_data:

networks:
  springboot-postgresql-network:
    name: springboot-postgresql-network
    external: true
